# Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [ ]:
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
# Create a Series from a list
data = [1,2,3,4,5]
series = pd.Series(data) # index will be automatically created as 0,1,2,3,4
print(f"Series from list:\n{series}\n")
type(series)

Series from list:
0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

In [ ]:
# Create a series from a dictionary
data_dict = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data_dict) # keys becomes index and values becomes data
print(f"Series from dictionary:\n{series_dict}\n")
type(series_dict)

Series from dictionary:
a    1
b    2
c    3
dtype: int64

pandas.core.series.Series

In [8]:
data = [10,20,30,40,50]
index = ['a','b','c','d','e']
series_index = pd.Series(data, index=index) # index will be created as a,b,c,d,e
print(f"Series with custom index:\n{series_index}\n")

Series with custom index:
a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
# DataFrame
# A Pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). 
# It is similar to a spreadsheet or SQL table.

# Create a DataFrame from a dictionary of lists
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Tokyo']
}
df = pd.DataFrame(data_dict)
print(f"DataFrame from dictionary:\n{df}\n")
type(df)


import numpy as np
np.array(df)

DataFrame from dictionary:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

array([['Alice', 25, 'New York'],
       ['Bob', 30, 'London'],
       ['Charlie', 35, 'Tokyo']], dtype=object)

In [13]:
# create a DataFrame from a list of dictionaries
data_list = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Tokyo'}
]
df = pd.DataFrame(data_list)
print(f"DataFrame from list of dictionaries:\n{df}\n")

DataFrame from list of dictionaries:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [19]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [18]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [63]:
# Accessing data from DataFrame
data_list = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Tokyo'}
]
df = pd.DataFrame(data_list)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [59]:
df['Name'] # Accessing a column

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [28]:
df[['Name', 'City']] # Accessing multiple columns

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Tokyo

In [34]:
df.loc[0, 'Name'] # Accessing a specific cell by row and column labels

'Alice'

In [36]:
df.iloc[0] # Accessing a row by position

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
# Difference between loc and iloc
# loc is label-based, which means that you have to specify the name of the row or column that you want to access. 
# iloc is integer position-based, which means that you have to specify the index of the row or column that you want to access.

In [40]:
# Accessing a specified element
print(f"Age at row 1: {df.at[1,'Age']}") # Accessing a specific cell by row and column labels

Age at row 1: 30

In [42]:
# Accessing a specified element using iat
print(f"Age at row 1: {df.iat[1,1]}") # Accessing a specific cell by row and column position

Age at row 1: 30

In [64]:
# Data Manupulation with DataFrame

df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [65]:
# Adding a new column to the DataFrame
df['Salary'] = [50000, 60000, 70000] # Adding a new column
df

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000

In [66]:
# remove a column from the DataFrame
df.drop('Salary', axis=1, inplace=True) # Removing a column for column we have to specify axis=1, inplace=True will make the change in the original DataFrame
# to remove a row we have to specify axis=0
# inplace=True will make the change in the original DataFrame, 
# if inplace=False then it will return a new DataFrame with the column removed
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Tokyo

In [67]:
df['Age'] = df['Age'] + 1 # Accessing a column
df

      Name  Age      City
0    Alice   26  New York
1      Bob   31    London
2  Charlie   36     Tokyo

In [ ]:
# drop based on row index
df.drop(0, axis=0, inplace=True) # Removing a row for row we have to specify axis=0, 
# inplace=True will make the change in the original DataFrame
df

      Name  Age    City
1      Bob   31  London
2  Charlie   36   Tokyo

In [ ]:
# Reading data from a CSV file
import pandas as pd
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [73]:
df.describe() # Get summary statistical summary of the DataFrame

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000