# Reading Data From Different Sources

In [1]:
import pandas as pd
from io import StringIO # Importing StringIO to read JSON data from a string
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [4]:
df.to_json(orient='records') # Converting the DataFrame to JSON format with 'records' orientation 
# What is records orientation in pandas to_json method?
# The 'records' orientation in the pandas to_json method formats the JSON output as a list of dictionaries, 
# where each dictionary represents a row in the DataFrame. 
# Each key in the dictionary corresponds to a column name, and the value is the data for that column in that row. 
# This format is particularly useful for representing tabular data in JSON format, making it easy to read and work with in various applications.

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv') 
# Reading a CSV file from a URL and creating a DataFrame

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', header=None) 
# Reading a CSV file from a URL and creating a DataFrame, with header=None to indicate that the first row does not contain column names. 
# When header=None is used, pandas will automatically assign integer column names starting from 0 to the DataFrame.

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv').to_csv('titanic.csv', index=False)
# Saving the DataFrame to a CSV file named 'titanic.csv' without including the index column in the output file.

In [18]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df = pd.read_html(url)

In [ ]:
df # why is it printed as a list?
# The output is printed as a list because the pd.read_html() function returns a list of DataFrames. 
# Each DataFrame in the list corresponds to a table found in the HTML content of the specified URL.
# In this case, the URL contains multiple tables, and pd.read_html() has extracted all of them, resulting in a list of DataFrames. 
# If you want to access a specific table, you can index the list, for example, df[0] to access the first table.

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [20]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [22]:
url="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url,match="Country",header=0)[0]
# Reading tables from a Wikipedia page, matching the table that contains the header "Country" and using the first row as the header for the DataFrame.

HTTPError: HTTP Error 403: Forbidden

pd.read_html(url) is hitting Wikipedia directly with pandas’ default request, and Wikipedia is returning 403 Forbidden because that request looks too “bot-like”.

In [23]:
pd.read_html(
    url,
    match="Country",
    header=0,
    storage_options={"User-Agent": "Mozilla/5.0"},
)[0]
# Reading tables from a Wikipedia page, matching the table that contains the header "Country" and using the first row as the header for the DataFrame, 
# while also specifying a custom User-Agent in the storage options to avoid potential issues with web scraping.

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [26]:
df_excel = pd.read_excel('data.xlsx')

In [27]:
df_excel.to_pickle('data.pkl') # Saving the DataFrame to a pickle file named 'data.pkl' for later use.

In [28]:
pd.read_pickle('data.pkl') # Reading the DataFrame from the pickle file 'data.pkl' and loading it back into memory.

    Name  Age
0  Krish   32
1   Jack   34
2   John   31